# Visit https://github.com/lowlighter/metrics#-documentation for full reference

# Your GitHub token
# The following scopes are required:
#  - public_access (default scope)
# The following additional scopes may be required:
#  - read:org      (for organization related metrics)
#  - read:user     (for user related data)
#  - read:packages (for some packages related data)
#  - repo          (optional, if you want to include private repositories)

name: Metrics

on:
  schedule: [{cron: "59 23 * * 0"}]   # Schedule updates (each hour)
  workflow_dispatch:                  # Lines below let you run workflow manually and on each commit
  # push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      - name: Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, community, metadata
          user: JosManoel
          template: classic
          config_timezone: America/Sao_Paulo
          output_action: gist
          committer_gist: ${{ secrets.METRICS_GIST }}
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css, HLSL, Jupyter Notebook, ShaderLab
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%


      - name: Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JosManoel
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          output_action: gist
          committer_gist: ${{ secrets.METRICS_GIST }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 5
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
