# Visit https://github.com/lowlighter/metrics#-documentation for full reference

# Your GitHub token
# The following scopes are required:
#  - public_access (default scope)
# The following additional scopes may be required:
#  - read:org      (for organization related metrics)
#  - read:user     (for user related data)
#  - read:packages (for some packages related data)
#  - repo          (optional, if you want to include private repositories)

name: Metrics

on:
  schedule: [{cron: "59 23 * * 0"}]   # Schedule updates (each hour)
  workflow_dispatch:                  # Lines below let you run workflow manually and on each commit
  # push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    
      - name: Achievements and Activity
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JosManoel
          template: classic
          base: activity, community, repositories
          config_timezone: America/Sao_Paulo
          output_action: gist
          committer_gist: ${{ secrets.METRICS_GIST }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 12
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: starred   


      - name: Metrics and lines
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics_full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JosManoel
          template: classic
          base: metadata
          config_timezone: America/Sao_Paulo
          output_action: gist
          committer_gist: ${{ secrets.METRICS_GIST }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage, byte-size
          plugin_languages_ignored: Jupyter Notebook, HTML, CSS
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_delay: 2
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: history
          repositories_forks: yes
